In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [5]:
# 5차원의 단어 벡터
# 문장의 길이 : 4
train_X = [
    [0.1, 4.2, 1.5, 1.1, 2.8], 
    [1.0, 3.1, 2.5, 0.7, 1.1], 
    [0.3, 2.1, 1.5, 2.1, 0.1], 
    [2.2, 1.4, 0.5, 0.9, 1.1]
    ]
print(np.shape(train_X))

(4, 5)


In [40]:
# RNN은 2D Tensor가 아닌 3D Tensor 입력 받음
# 배치 크기 1을 추가해 3D Tensor로 변경
# batch_size는 한 번에 RNN이 학습하는 데이터의 양, 샘플이 1개 이므로 1
train_X = [
    [[0.1, 4.2, 1.5, 1.1, 2.8],
     [1.0, 3.1, 2.5, 0.7, 1.1], 
     [0.3, 2.1, 1.5, 2.1, 0.1], 
     [2.2, 1.4, 0.5, 0.9, 1.1]]
    ]

# numpy array로 변환
train_X = np.array(train_X, dtype=np.float32)
print(np.shape(train_X))

(1, 4, 5)


## SimpleRNN

In [41]:
print(np.shape(train_X))
train_X

(1, 4, 5)


array([[[0.1, 4.2, 1.5, 1.1, 2.8],
        [1. , 3.1, 2.5, 0.7, 1.1],
        [0.3, 2.1, 1.5, 2.1, 0.1],
        [2.2, 1.4, 0.5, 0.9, 1.1]]], dtype=float32)

In [49]:
rnn = SimpleRNN(3, return_sequences=False, return_state=False)
hidden_state = rnn(train_X)

print(f'hidden state : {hidden_state}, shape: {hidden_state.shape}')

hidden state : [[-0.9970525   0.93823165  0.8588747 ]], shape: (1, 3)


In [51]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print(f'hidden state : {hidden_states}, shape: {hidden_states.shape}')


hidden state : [[[-0.9999829   0.99460703  0.07401923]
  [-0.9998104   0.99197096  0.97708225]
  [-0.9791244   0.5433944   0.8172264 ]
  [-0.99488074  0.90221334  0.93430704]]], shape: (1, 4, 3)


In [52]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print(f'hidden states : {hidden_states}, shape: {hidden_states.shape}')
print(f'last hidden state : {last_state}, shape: {last_state.shape}')

hidden states : [[[-0.9999829   0.99460703  0.07401923]
  [-0.99838936  0.99902976  0.9854075 ]
  [-0.8120765   0.96927166  0.51177096]
  [-0.93273544  0.9777664   0.84414005]]], shape: (1, 4, 3)
last hidden state : [[-0.93273544  0.9777664   0.84414005]], shape: (1, 3)


In [53]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print(f'hidden state : {hidden_state}, shape: {hidden_state.shape}')
print(f'last hidden state : {last_state}, shape: {last_state.shape}')

hidden state : [[-0.97541666  0.84519523 -0.5688779 ]], shape: (1, 3)
last hidden state : [[-0.97541666  0.84519523 -0.5688779 ]], shape: (1, 3)
